-- MySQL Script generated by MySQL Workbench
-- Wed Nov 18 07:49:53 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fosterlister_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fosterlister_db` ;

-- -----------------------------------------------------
-- Schema fosterlister_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fosterlister_db` DEFAULT CHARACTER SET utf8 ;
USE `fosterlister_db` ;

-- -----------------------------------------------------
-- Table `fosterlister_db`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fosterlister_db`.`users` ;

CREATE TABLE IF NOT EXISTS `fosterlister_db`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `address` TEXT NOT NULL,
  `number_pets` INT UNSIGNED NOT NULL,
  `phone` VARCHAR(25) NOT NULL,
  `is_admin` TINYINT UNSIGNED NOT NULL,
  `image_url` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `password_UNIQUE` (`password` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fosterlister_db`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fosterlister_db`.`roles` ;

CREATE TABLE IF NOT EXISTS `fosterlister_db`.`roles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fosterlister_db`.`users_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fosterlister_db`.`users_roles` ;

CREATE TABLE IF NOT EXISTS `fosterlister_db`.`users_roles` (
  `user_id` INT UNSIGNED NOT NULL,
  `role_id` INT UNSIGNED NOT NULL,
  INDEX `userId_idx` (`user_id` ASC),
  INDEX `roleId_idx` (`role_id` ASC),
  CONSTRAINT `userId`
    FOREIGN KEY (`user_id`)
    REFERENCES `fosterlister_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `roleId`
    FOREIGN KEY (`role_id`)
    REFERENCES `fosterlister_db`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fosterlister_db`.`listings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fosterlister_db`.`listings` ;

CREATE TABLE IF NOT EXISTS `fosterlister_db`.`listings` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `image_url` TEXT NULL,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(10) NOT NULL,
  `breed` VARCHAR(45) NOT NULL,
  `dob` VARCHAR(255) NOT NULL,
  `gender` CHAR(1) NOT NULL,
  `conditions` TEXT NULL,
  `description` TEXT NOT NULL,
  `size` VARCHAR(15) NOT NULL,
  `litter_size` INT UNSIGNED NULL,
  `foster_duration` VARCHAR(45) NULL,
  `created_time` DATETIME NOT NULL,
  `role_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `user_id_idx` (`user_id` ASC),
  INDEX `role_id_idx` (`role_id` ASC),
  CONSTRAINT `listing_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `fosterlister_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `listing_role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `fosterlister_db`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fosterlister_db`.`requests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fosterlister_db`.`requests` ;

CREATE TABLE IF NOT EXISTS `fosterlister_db`.`requests` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `listing_id` INT UNSIGNED NOT NULL,
  `request_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `user_id_idx` (`user_id` ASC),
  INDEX `listing_id_idx` (`listing_id` ASC),
  CONSTRAINT `request_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `fosterlister_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `request_listing_id`
    FOREIGN KEY (`listing_id`)
    REFERENCES `fosterlister_db`.`listings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fosterlister_db`.`volunteers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fosterlister_db`.`volunteers` ;

CREATE TABLE IF NOT EXISTS `fosterlister_db`.`volunteers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `title` TEXT NOT NULL,
  `description` TEXT NULL,
  `contact` TEXT NULL,
  `image_url` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `user_id_idx` (`user_id` ASC),
  CONSTRAINT `volunteer_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `fosterlister_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
